default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_experience_development

test:
  <<: *default
  database: my_experience_test

production:
  <<: *default
  database: my_experience_production
  username: my_experience
  password: <%= ENV['MY_EXPERIENCE_DATABASE_PASSWORD'] %>
